### ISSUE TITLE
CRD conversion webhook does`n work in OpenShift 4

### ISSUE THREAD

**Issue by dkhachyan** [minio/operator#561]
Hi!
Operator successfully requests certificate and creates operator-tls secret, but API Server can't connect with tls handshake errors:

kubeAPI Server logs:
```
E0329 12:22:47.251683       1 cacher.go:428] unexpected ListAndWatch error: storage/cacher.go:/minio.min.io/tenants: Failed to list minio.min.io/v1, Kind=Tenant: conversion webhook for minio.min.io/v2, Kind=Tenant failed: Post https://operator.minio.svc:4222/webhook/v1/crd-conversion?timeout=30s: x509: certificate signed by unknown authority
E0329 12:22:48.262488       1 cacher.go:428] unexpected ListAndWatch error: storage/cacher.go:/minio.min.io/tenants: Failed to list minio.min.io/v1, Kind=Tenant: conversion webhook for minio.min.io/v2, Kind=Tenant failed: Post https://operator.minio.svc:4222/webhook/v1/crd-conversion?timeout=30s: x509: certificate signed by unknown authority
E0329 12:22:49.270843       1 cacher.go:428] unexpected ListAndWatch error: storage/cacher.go:/minio.min.io/tenants: Failed to list minio.min.io/v1, Kind=Tenant: conversion webhook for minio.min.io/v2, Kind=Tenant failed: Post https://operator.minio.svc:4222/webhook/v1/crd-conversion?timeout=30s: dial tcp 10.253.80.11:4222: connect: connection refused
```
Minio Operator logs:
```
2021/03/29 12:24:40 http: TLS handshake error from 10.253.0.1:48266: remote error: tls: bad certificate
2021/03/29 12:24:40 http: TLS handshake error from 10.253.32.1:40244: remote error: tls: bad certificate
2021/03/29 12:24:41 http: TLS handshake error from 10.253.16.1:46478: remote error: tls: bad certificate
2021/03/29 12:24:41 http: TLS handshake error from 10.253.0.1:48276: remote error: tls: bad certificate
2021/03/29 12:24:41 http: TLS handshake error from 10.253.32.1:40252: remote error: tls: bad certificate
2021/03/29 12:24:42 http: TLS handshake error from 10.253.16.1:46486: remote error: tls: bad certificate
2021/03/29 12:24:42 http: TLS handshake error from 10.253.32.1:40260: remote error: tls: bad certificate
2021/03/29 12:24:43 http: TLS handshake error from 10.253.0.1:48294: remote error: tls: bad certificate
```

## Environment
* Minio Version: RELEASE.2021-03-17T02-33-02Z
* MinIO Operator Version: 4.0.3
* Server setup and configuration: OpenShift 4.7
* Operating System and version: FCOS 33
* Kernel version: 5.10.12-200.fc33.x86_64

**Comment by dkhachyan** [comment]
Maybe we need to change signer to kubernetes.io/kube-apiserver-client

Now kubernetes.io/legacy-unknown is used

Example:
```
Spec: certificates.CertificateSigningRequestSpec{
			Request: encodedBytes,
			Groups:  []string{"system:authenticated"},
			Usages: []certificates.KeyUsage{
				certificates.UsageDigitalSignature,
				certificates.UsageServerAuth,
				certificates.UsageClientAuth,
                        SignerName: signerName,  // kubernetes.io/kube-apiserver-client
		        }
```

**Comment by liyimeng** [comment]
@harshavardhana I think it is the same issue in #651 
We should have a look into this.

**Comment by harshavardhana** [comment]
> @harshavardhana I think it is the same issue in #651
> We should have a look into this.

No it is not the same @liyimeng

**Comment by liyimeng** [comment]
@harshavardhana Hmm, you are right. It looks close but different.  #651 is more like #657. Something I just observe is that my cluster get an automatically k3s upgrade when it restarted from power failure. 

But I don't fully understand how #657 is resolved.

**Comment by harshavardhana** [comment]
> @harshavardhana Hmm, you are right. It looks close but different.  #651 is more like #657. Something I just observe is that my cluster get an automatically k3s upgrade when it restarted from power failure. 
> 
> But I don't fully understand how #657 is resolved. 
> 

The issue is in k3s and they have recently fixed it.

**Comment by liyimeng** [comment]
@harshavardhana Thanks a lot for the clarification!

**Comment by ShayBenyo11** [comment]
Still facing this issue. Using latest 4.6.7 operator, is there any other solution or possibilites of why's it happening?

**Comment by ShayBenyo11** [comment]
Sorry, I mean 4.3.7 operator, and in some OCP 4.6.35 Clusters it working and the same procedure in another clusters with the same versions and same actions creates those errors

**Comment by dvaldivia** [comment]
@ShayBenyo11 can you confirm if CSR's are working on the clusters that the conversion webhook is not working? If we cannot get a certificate for operator via CSRs the webhook will fail, we've seen this as a common problem
