### ISSUE TITLE
Minio Operator v4.2.5: no matches for kind "Operator" in version "minio.min.io/v2"

### ISSUE THREAD

**Issue by HaehnleinMar** [minio/operator#819]
## Expected Behavior
Operator should be able to create operator-tls secret.
Possibly a dupe of #746 and #726 #520.
The behavior is also described in [this comment](https://github.com/minio/operator/issues/708#issuecomment-898264188).

## Current Behavior
When deploying the Operator using `kubectl minio init` it deploys the operator, but cannot create `secret/operator-tls`.

```
I0908 09:00:56.763031       1 main.go:74] Starting MinIO Operator
I0908 09:00:57.115799       1 main.go:146] caBundle on CRD updated
I0908 09:00:57.116409       1 main-controller.go:268] Setting up event handlers
I0908 09:00:57.116508       1 main-controller.go:681] Starting Tenant controller
I0908 09:00:57.116522       1 main-controller.go:684] Waiting for informer caches to sync
I0908 09:00:57.144105       1 main-controller.go:632] operator TLS secret not found%!(EXTRA string=secrets "operator-tls" not found)
I0908 09:00:57.227435       1 csr.go:145] Start polling for certificate of csr/operator-minio-operator-csr, every 5s, timeout after 20m0s
I0908 09:00:57.316866       1 main-controller.go:689] Starting workers
I0908 09:01:02.236353       1 csr.go:170] Certificate successfully fetched, creating secret with Private key and Certificate
E0908 09:01:02.239573       1 operator.go:161] Unexpected error during the creation of the secret/operator-tls: secrets "operator-tls" is forbidden: cannot set blockOwnerDeletion in this case because cannot find RESTMapping for APIVersion minio.min.io/v2 Kind Operator: no matches for kind "Operator" in version "minio.min.io/v2"
I0908 09:01:02.239606       1 main-controller.go:634] Waiting for the operator certificates to be issued secrets "operator-tls" is forbidden: cannot set blockOwnerDeletion in this case because cannot find RESTMapping for APIVersion minio.min.io/v2 Kind Operator: no matches for kind "Operator" in version "minio.min.io/v2"
```

## Possible Solution
The creation fails because there is no CRD `minio.min.io/v2/Operator`. Adding that could fix it (?)

## Steps to Reproduce (for bugs)
1. `kubectl minio init`
2. `kubectl get pods -n minio-operator`
3. `kubectl logs -n minio-operator minio-operator-<...>`

## Context
I cannot currently deploy a working Minio Operator on OKD 4.7. 

## Your Environment

* Version used (`minio-operator`): v4.2.5
* Environment name and version (e.g. kubernetes v1.17.2): OKD 4.7.0 (k8s v1.20.0)

**Comment by dnskr** [comment]
Hi!
Have you seen this [doc](https://docs.min.io/minio/k8s/deployment/deploy-minio-operator.html#kubernetes-tls-certificate-api)?
I have the same issue with OpenShift (OKD is related to OpenShift as I understand), so I think the issue might be on the environment side. Also other users have the issue running minio operator with Rancher.

To deploy minio operator you can disable generating TLS by setting env variable ([PR#713](https://github.com/minio/operator/pull/713)):
```
MINIO_OPERATOR_TLS_ENABLE=off
```
Let me know if it helps.

**Comment by bahetiamit** [comment]
This issue is resolved by PR - https://github.com/minio/operator/pull/788. I tried it on Redhat OCP. Disabling TLS security was not an option for me. Hope that helps!

**Comment by harshavardhana** [comment]
Please test with v4.2.7

**Comment by bahetiamit** [comment]
v4.2.7 still has the same issue with owner reference of secret on Redhat OCP. 

`I0914 04:03:59.010776       1 csr.go:235] Certificate successfully fetched, creating secret with Private key and Certificate
E0914 04:03:59.015856       1 operator.go:249] Unexpected error during the creation of the secret/operator-tls: secrets "operator-tls" is forbidden: cannot set blockOwnerDeletion in this case because cannot find RESTMapping for APIVersion minio.min.io/v2 Kind Operator: no matches for kind "Operator" in version "minio.min.io/v2"`

Owner reference for secret _operator-tls_ needs a fix either by setting owner as "Deployment" as done in PR https://github.com/minio/operator/pull/788  or by creating "Operator" as per the error message.

CSR API version was never a problem as certificates were getting created with CSR V1 as well.

**Comment by HaehnleinMar** [comment]
@dnskr I tried disabling TLS, but that is not an option.

@harshavardhana I still get the same error with v4.2.7:

```
I0914 07:46:08.633577       1 operator.go:100] operator TLS secret not found: secrets "operator-tls" not found
W0914 07:46:08.637679       1 warnings.go:70] certificates.k8s.io/v1beta1 CertificateSigningRequest is deprecated in v1.19+, unavailable in v1.22+; use certificates.k8s.io/v1 CertificateSigningRequest
W0914 07:46:08.662116       1 warnings.go:70] certificates.k8s.io/v1beta1 CertificateSigningRequest is deprecated in v1.19+, unavailable in v1.22+; use certificates.k8s.io/v1 CertificateSigningRequest
W0914 07:46:08.673611       1 warnings.go:70] certificates.k8s.io/v1beta1 CertificateSigningRequest is deprecated in v1.19+, unavailable in v1.22+; use certificates.k8s.io/v1 CertificateSigningRequest
I0914 07:46:08.673811       1 csr.go:192] Start polling for certificate of csr/operator-minio-operator-csr, every 5s, timeout after 20m0s
W0914 07:46:13.678395       1 warnings.go:70] certificates.k8s.io/v1beta1 CertificateSigningRequest is deprecated in v1.19+, unavailable in v1.22+; use certificates.k8s.io/v1 CertificateSigningRequest
I0914 07:46:13.678586       1 csr.go:235] Certificate successfully fetched, creating secret with Private key and Certificate
E0914 07:46:13.681110       1 operator.go:249] Unexpected error during the creation of the secret/operator-tls: secrets "operator-tls" is forbidden: cannot set blockOwnerDeletion in this case because cannot find RESTMapping for APIVersion minio.min.io/v2 Kind Operator: no matches for kind "Operator" in version "minio.min.io/v2"
I0914 07:46:13.681133       1 operator.go:102] Waiting for the operator certificates to be issued secrets "operator-tls" is forbidden: cannot set blockOwnerDeletion in this case because cannot find RESTMapping for APIVersion minio.min.io/v2 Kind Operator: no matches for kind "Operator" in version "minio.min.io/v2"
```

**Comment by HaehnleinMar** [comment]
And yes, OKD is the Open Source version of OpenShift, like wildfly is to Red Hat JBoss Enterprise Application Platform or Keycloak is to Red Hat SSO.
